### PR TITLE
[TUBEMQ-233] Performance Improvement on FileSegmentList

### PR DESCRIPTION
**Pull request by hystericalhell**
**Still Prototype**  for review first.
Implement segmentList2 replacing native compact array segmentList by using RoundQueue, which brings the flexibility on element modification, and making use of weak CAS to better adapt multi-threaded runtime.

### CODE REVIEW

**Comment by Technoboy-** [comment]
It's better not to involve the new dependency - hppc, for it's not maintained for a long time.

**Comment by hystericalhell** [comment]
> It's better not to involve the new dependency - hppc, for it's not maintained for a long time.

Hi Technoboy,

As shown on Maven's repo, the latest hppc 0.8.2 is updated in Jun 2020, and it shows the recent update is just 9 days ago, do you have any formal announcement about they *give up* this project, or any proof about it's out-of-maintenance?
Maven Repo: [HPPC](https://mvnrepository.com/artifact/com.carrotsearch/hppc)
GitHub: [HPPC](https://github.com/carrotsearch/hppc)

Moreover, if you have any better alternative than HPPC, it would be very welcomed, please advise.

Best regards,
Gabriel

**Comment by Technoboy-** [comment]
> > It's better not to involve the new dependency - hppc, for it's not maintained for a long time.
> 
> Hi Technoboy,
> 
> As shown on Maven's repo, the latest hppc 0.8.2 is updated in Jun 2020, and it shows the recent update is just 9 days ago, do you have any formal announcement about they _give up_ this project, or any proof about it's out-of-maintenance?
> Maven Repo: [HPPC](https://mvnrepository.com/artifact/com.carrotsearch/hppc)
> GitHub: [HPPC](https://github.com/carrotsearch/hppc)
> 
> Moreover, if you have any better alternative than HPPC, it would be very welcomed, please advise.
> 
> Best regards,
> Gabriel

Yes, I re-checked it .

**Comment by gosonzhang** [comment]
I suggest not to merge this PR

This change uses the ObjectArrayDeque class to pre-allocate array elements, and uses AtomicBoolean's weakCompareAndSet method to modify and delete the segmentList2 object to be preempted. Compared with before modification: ObjectArrayDeque implementation can improve the performance of new and delete operations; using AtomicBoolean to solve the multi-thread preemption phase, I personally think that there should not be much improvement, the use of AtomicReference should be more perfect.

Personally, from the overall point of view of the system, the performance loss formed by this point is not particularly large, ant it has experienced several years of online operation scenarios and has been relatively stable; the new changes will affect the overall, and the improvement of performance is temporarily unknown, so it is a better choice to temporarily not merge it.

**Comment by gosonzhang** [comment]
I'll close this pr, thanks  @hystericalhell

**Pull request closed without merging**
