### PR TITLE
correct DefaultLoadBalancer#balance rejGroupClientINfoMap -> rejGroupClientInfoMap

### PR DESCRIPTION
**Pull request by Technoboy-**
https://issues.apache.org/jira/browse/TUBEMQ-20

### CODE REVIEW

**Comment by Technoboy-** [comment]
@TisonKun

**Comment by gosonzhang** [comment]
@Technoboy-, before you mention PR, you need to update the integration based on the master‘s latest code. I found that many accepted contents are included again in this PR, such as 81f9350, 30d77ff, ee99d06 have been integrated, which will make the committer very confused，Which one was realy modified this time?

**Comment by TisonKun** [comment]
Yes I second by @gosonzhang . This time I help with squash and merge but @Technoboy- you should have taken the work by yourself.

**Comment by TisonKun** [comment]
Another problem is that you'd better keep the title & commit log with the format `[TUBEMQ-XXX][optional component] ...`.

**Comment by Technoboy-** [comment]
@TisonKun 

> @Technoboy-, before you mention PR, you need to update the integration based on the master‘s latest code. I found that many accepted contents are included again in this PR, such as [81f9350](https://github.com/apache/incubator-tubemq/commit/81f9350d355ad3b788c15c0ae254b822cb983849), [30d77ff](https://github.com/apache/incubator-tubemq/commit/30d77ffded6624f53948285d8e897424237dee9e), [ee99d06](https://github.com/apache/incubator-tubemq/commit/ee99d06abec9505a70232d57a7c692f2e53e1472) have been integrated, which will make the committer very confused，Which one was realy modified this time?

ok

**Comment by Technoboy-** [comment]
> Another problem is that you'd better keep the title & commit log with the format `[TUBEMQ-XXX][optional component] ...`.

ok, forgot to comment on commit log

**Comment by Wang-Richy** [comment]
已成功领取本issue

**Pull request merged**
