### PR TITLE
[TUBEMQ-433] add tubemq perf-consumer/producer scripts

### PR DESCRIPTION
**Pull request by yuanboliu**

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]
+1

**Review by gosonzhang — COMMENTED** [review]
We need to unify the parameter labels of the CLI to reduce the learning cost of users. I will give a fields definition later

**Review by gosonzhang — CHANGES_REQUESTED** [review]
Hi @yuanboliu 

For CLI parameter names, unless it is our own attribute definition, do we try to align it with Kafka as much as possible?
For example, the size of the message, the number of messages, etc. As a user of MQ, I believe everyone has used Kafka, so if we can reduce the learning cost as much as possible, our product will be very user-friendly

like this:
image

**Comment by yuanboliu** [comment]
ok, I'll update this pr today

**Comment by yuanboliu** [comment]
@gosonzhang 
sh tubemq-producer-perf-test.sh
sh tubemq-consumer-perf-test.sh 

image
image

```sh
[2020-12-02 15:15:07,974] INFO [Producer] Producer status from ready to running! (org.apache.tubemq.client.producer.ProducerManager)
[2020-12-02 15:15:07,983] INFO [Publish begin 2] publish topicSet [teg_inner_drtest1], address = org.apache.tubemq.client.producer.ProducerManager@583562e5 (org.apache.tubemq.client.producer.ProducerManager)
[2020-12-02 15:15:07,991] INFO [Publish begin 2] already get meta info, topicSet: [teg_inner_drtest1], waste time 7 Ms (org.apache.tubemq.client.producer.ProducerManager)
[2020-12-02 15:15:11,153] INFO Send 1000 message, keyCount is 251 (org.apache.tubemq.example.MAMessageProducerExample)
[2020-12-02 15:15:11,656] INFO Send 2000 message, keyCount is 501 (org.apache.tubemq.example.MAMessageProducerExample)
[2020-12-02 15:15:12,526] INFO Send 3000 message, keyCount is 751 (org.apache.tubemq.example.MAMessageProducerExample)
[2020-12-02 15:15:12,950] INFO Send 4000 message, keyCount is 1001 (org.apache.tubemq.example.MAMessageProducerExample)
[2020-12-02 15:15:14,990] INFO Send 5000 message, keyCount is 1251 (org.apache.tubemq.example.MAMessageProducerExample)
[2020-12-02 15:15:18,017] INFO Send 6000 message, keyCount is 1501 (org.apache.tubemq.example.MAMessageProducerExample)
[2020-12-02 15:15:18,832] INFO Send 7000 message, keyCount is 1751 (org.apache.tubemq.example.MAMessageProducerExample)
```

```sh
[2020-12-02 15:39:07,835] INFO Starting Fetch Worker Pool ! (org.apache.tubemq.client.consumer.MessageFetchManager)
[2020-12-02 15:39:07,835] INFO Prepare to start Fetch Worker Pool, total count:1024 (org.apache.tubemq.client.consumer.MessageFetchManager)
[2020-12-02 15:39:07,901] INFO Fetch Worker Pool started ! (org.apache.tubemq.client.consumer.MessageFetchManager)
[2020-12-02 15:32:31,844] INFO Receive messages:63000 (org.apache.tubemq.example.MsgRecvStats)
[2020-12-02 15:33:41,768] INFO Receive messages:116000 (org.apache.tubemq.example.MsgRecvStats)
[2020-12-02 15:34:25,348] INFO Receive messages:148000 (org.apache.tubemq.example.MsgRecvStats)
[2020-12-02 15:34:52,044] INFO Receive messages:168000 (org.apache.tubemq.example.MsgRecvStats)
[2020-12-02 15:35:00,441] INFO Receive messages:174000 (org.apache.tubemq.example.MsgRecvStats)
```

**Review by gosonzhang — APPROVED** [review]

**Comment by gosonzhang** [comment]
@yuanboliu  Thanks!

Version 0.7.0 is being released, and I will merge it later.

**Pull request merged**
