### PR TITLE
TUBEMQ-10 javadoc error

### PR DESCRIPTION
**Pull request by Technoboy-**
https://issues.apache.org/jira/browse/TUBEMQ-10

### CODE REVIEW

**Comment by chenjunjiedada** [comment]
LGTM

**Comment by kaynewu** [comment]
+1

**Comment by TisonKun** [comment]
Hi @chenjunjiedada , please prefer "Squash And Merge" which doesn't produce a redundant merge commit.

We are discussing on dev mailing list about how to handle contribution and merging commits. Feel free to share your idea there but don't rush into merging prs.

**Comment by TisonKun** [comment]
FYI https://lists.apache.org/x/thread.html/rb478cc59ca720d1ca9a6c1a2616108383fc7735a770284afe56d508b@%3Cdev.tubemq.apache.org%3E

cc @yiheng

**Pull request merged**
