### PR TITLE
[TUBEMQ-300] Update LICENSE [addendum]

### PR DESCRIPTION
**Pull request by gosonzhang**

### CODE REVIEW

**Comment by netroby** [comment]
Why not apache license?

MIT license?

**Comment by gosonzhang** [comment]
The TubeMQ LICENSE is not changed, still Apache V2. This is the description of the external code LICENSE referenced by the project, include:
1. the reference's source code, 
2. come from where, 
3. what is the category and content of the LICENSE

So, @netroby, you see the MIT's statement

**Comment by guangxuCheng** [comment]
@justinmclean can you take a look? We are preparing to release the next version. Thanks

**Review by guangxuCheng — APPROVED** [review]
+1

**Comment by guangxuCheng** [comment]
Preparing to release the next version, Merge firstly.

**Pull request merged**
