### PR TITLE
TUBEMQ-7: Using StringBuilder instead of StringBuffer in BaseResult

### PR DESCRIPTION
**Pull request by Technoboy-**

### CODE REVIEW

**Comment by gosonzhang** [comment]
@Technoboy- Can you pull a issue first and include the issue-id in the PR name?

**Comment by Technoboy-** [comment]
> @Technoboy- Can you pull a issue first and include the issue-id in the PR name?

But where is the issue tag ?

**Comment by TisonKun** [comment]
> > @Technoboy- Can you pull a issue first and include the issue-id in the PR name?
> 
> But where is the issue tag ?

https://issues.apache.org/jira/projects/TUBEMQ/issues

@Technoboy- TubeMQ uses JIRA as issue tracker. Hopefully we will have a CONTRIBUTE guide soon later.

**Comment by TisonKun** [comment]
@Technoboy- Here is a guide how to file an issue on JIRA https://confluence.atlassian.com/jiracoreserver073/creating-issues-and-sub-tasks-861257329.html

**Comment by Technoboy-** [comment]
> > > @Technoboy- Can you pull a issue first and include the issue-id in the PR name?
> > 
> > 
> > But where is the issue tag ?
> 
> https://issues.apache.org/jira/projects/TUBEMQ/issues
> 
> @Technoboy- TubeMQ uses JIRA as issue tracker. Hopefully we will have a CONTRIBUTE guide soon later.

How about using github ?  It's more convenient for user. 
As many projects start with JIRA, but change to github in the end. like "Apache Helix"

**Comment by TisonKun** [comment]
@Technoboy- Yes it could be a choice. Actually the community has discussed about this before[1]. You can participant the discussion or start a new thread, and share your idea. The community might switch to GitHub issue if there is a convincing reason.

[1] https://lists.apache.org/x/thread.html/b1d46bd289d38bdd2f27fff2af7dba879fc53767b536b4ca9a6cdcf6@%3Cdev.tubemq.apache.org%3E

**Comment by TisonKun** [comment]
BTW, the Apache way says all discussions happens on mailing list, so it is highly recommended to subscribe the mailing list[1] and discuss anything you want to.

[1] mailto:dev-subscribe@tubemq.apache.org

**Comment by Technoboy-** [comment]
All right , I will create a JIRA issue later.

**Comment by TisonKun** [comment]
Thanks for your contribution @Technoboy- !

**Pull request merged**
